# Generated by Django 5.2.6 on 2025-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('private_lander', 'private_lander'), ('borrower', 'borrower')], null=True),
        ),
    ]
