# Generated by Django 5.2.6 on 2025-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_forgotpasswordmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
