# Generated by Django 5.2.6 on 2025-09-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customusermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
